name: Format Code

on: [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Format code with black
        run: |
          pip install black
          black .
      - name: Sort imports with isort
        run: |
          pip install isort
          isort .
      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: PythonFormatter
          author_email: PythonFormatter@users.noreply.github.com
          message: "Format code with black"
          add: "."
